### PR TITLE
Update Azure.RSV.ReplicationAlert.md

### PR DESCRIPTION
**Pull request by aavdberg**
Location is read-only in Bicep

## PR Checklist

- [ ] PR has a meaningful title
- [ ] Summarized changes
- [ ] Change is not breaking
- [ ] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [ ] Unit tests created/ updated
  - [ ] Rule documentation created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by aavdberg** [comment]
image

**Comment by BernieWhite** [comment]
@aavdberg Nice catch. Thanks for opening a PR for this.

**Review by BernieWhite — APPROVED** [review]
Thanks @aavdberg. All good to merge.

**Comment by aavdberg** [comment]
Hi @BernieWhite is this repo also active in the [HACKTOBERFEST](https://hacktoberfest.com/)

**Comment by BernieWhite** [comment]
> Hi @BernieWhite is this repo also active in the [HACKTOBERFEST](https://hacktoberfest.com/)

Yes, you should see contributions counted. Let me know if not.

**Pull request merged**
