### PR TITLE
feat(new): Added Azure.LogAnalytics.Replication

### LINKED ISSUE #2893: [RULE] Log Analytics workspaces should have workspace replication enabled to improve service availability
### Existing rule

_No response_

### Suggested rule

Log Analytics workspaces supports workspace replication.
Workspace replication provides availability of the workspace in a secondary region and provides service availability if the primary region goes offline by changing the DNS records to point to the secondary workspace.

### Pillar

Reliability

### Additional context

https://azure.microsoft.com/updates/log-analytics-workspace-replication-public-preview
https://learn.microsoft.com/azure/azure-monitor/logs/workspace-replication

### PR DESCRIPTION
**Pull request by BenjaminEngeset**
## PR Summary

Fixes #2893

Added Azure.LogAnalytics.Replication.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by BenjaminEngeset** [comment]
Hi @BernieWhite,

Could you please share your thoughts on this? Initially, I believed that `Azure.Monitor.Workspace.Replication` was the appropriate approach. However, upon further consideration, I am wondering if it would be better to separate each “sub-service.” Given the extensive nature of the Azure Monitor portfolio and its potential for further growth, this might provide better scalability and organization.

**Review by BernieWhite — CHANGES_REQUESTED** [review]
Thanks @BenjaminEngeset. Great work.

There is a few suggestions below. Any questions let me know.

**Comment by BenjaminEngeset** [comment]
Check the latest changes @BernieWhite. Should be all good to merge.

**Review by BernieWhite — APPROVED** [review]
Thanks @BenjaminEngeset. All good to merge.

**Pull request merged**
