### PR TITLE
AML - disable local admin, behind vnet & idle shutdown

### PR DESCRIPTION
**Pull request by batemansogq**
## PR Summary

The initial set of AML rules
- disable local admin for compute
- compute hosted within a vnet
- compute idle shutdown

## PR Checklist

- [ ] PR has a meaningful title
- [ ] Summarized changes
- [ ] Change is not breaking
- [ ] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [ ] Unit tests created/ updated
  - [ ] Rule documentation created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by batemansogq** [comment]
accepted all of the suggestions - update minor text, corrected the ML User rule mkdwn

**Comment by BernieWhite** [comment]
> accepted all of the suggestions - update minor text, corrected the ML User rule mkdwn

:) Sorry i'm confused there is another PR #2475 that has some but not all of the rules.

I was planning to review this PR after that one was merged so that I didn't need to double up on reviewing the same files or should we just close the other PR and start a review here?

**Comment by batemansogq** [comment]
OK, lets close this and go again.

**Comment by batemansogq** [comment]
closing as advised.

**Pull request closed without merging**
