### PR TITLE
Added Azure.VM.SQLServerDisk

### LINKED ISSUE #9: IaaS SQL Servers only use premium disks
Check that IaaS SQL VMs only use premium disk.

### PR DESCRIPTION
**Pull request by bengeset96**
## PR Summary

Fixes #9 

Added Azure.VM.SQLServerDisk rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by bengeset96** [comment]
@BernieWhite 

Ready for review.

**Review by BernieWhite — CHANGES_REQUESTED** [review]
@bengeset96 Nice work! Just a few tweaks then all good to merge.

**Comment by bengeset96** [comment]
@BernieWhite 

Check latest changes, should be adjusted accordingly after the suggestions.

**Review by BernieWhite — APPROVED** [review]
Thanks @bengeset96 all good to merge.

**Pull request merged**
