### PR TITLE
feat(new): Added Azure.Firewall.AvailabilityZones

### LINKED ISSUE #2909: [RULE] Azure Firewall Should Be Deployed Across Availability Zones
### Existing rule

_No response_

### Suggested rule

Azure Firewall Should Be Deployed Across Availability Zones as per https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/azureFirewalls/#deploy-azure-firewall-across-multiple-availability-zones

### Pillar

Reliability

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BenjaminEngeset**
## PR Summary

Fixes #2909

Added Azure.Firewall.AvailabilityZones.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Review by BernieWhite — CHANGES_REQUESTED** [review]
Thanks @BenjaminEngeset. Double check my comments below. If there is any questions let me know. Tests and docs look good.

**Comment by BenjaminEngeset** [comment]
Thanks for the great feedback, @BernieWhite! Both the static method and the functions you created earlier were very helpful in developing this rule.

I’ve made some updates based on your input. Could you take a look now and let me know your thoughts?

**Comment by BenjaminEngeset** [comment]
@BernieWhite,

 We pushed at the same time and I pushed with force, saw the push notification from GitHub now.

Can you push it again?

**Comment by BenjaminEngeset** [comment]
> @BenjaminEngeset thanks for the updates. I made a few tweaks and added a test case for a region without AZ support. If you are happy with the changes we should be good to merge.
> 
> 
> 
> Great work!

Looks good! Let's merge.

**Pull request merged**
