### PR TITLE
feat(new): Added Azure.ACR.AnonymousAccess

### LINKED ISSUE #2422: Anonymous pull access should not be enabled
### Existing rule

_No response_

### Suggested rule

Create rule `Azure.ACR.AnonymousAccess` that checks if anonymous access is enabled.

If anonymous is enabled, the rule should fail.

By default, anonymous is not enabled but may be explicitly set to enabled by setting `properties.anonymousPullEnabled` to `true`.

Anonymous access can currently only be enabled on Standard and Premium tiers, and is a preview feature.

### Pillar

Security

### Additional context

- https://learn.microsoft.com/en-us/azure/well-architected/security/design-identity-authentication
- https://learn.microsoft.com/en-gb/azure/container-registry/anonymous-pull-access
- https://learn.microsoft.com/en-us/azure/templates/microsoft.containerregistry/registries?pivots=deployment-language-bicep

### PR DESCRIPTION
**Pull request by BenjaminEngeset**
## PR Summary

Fixes #2422

Added Azure.ACR.AnonymousAccess rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by BenjaminEngeset** [comment]
Hi @BernieWhite. This should be ready. I think the selector I created is not the most beautiful, but I didn't find any better way to solve it really with least possible code within the rule itself.

**Review by BernieWhite — APPROVED** [review]
Thanks @BenjaminEngeset. Looks good. I didn't have an issue with the two Premium/ Standard selectors. I've bumped the changes should.

Double check and let me know.

Otherwise all good.

**Comment by BenjaminEngeset** [comment]
Thanks @BernieWhite! Guess something went wrong then. So the concept with multiple selectors are that they work as an OR? First true means that no further checking and emits true?

Ready to merge.

**Comment by BernieWhite** [comment]
@BenjaminEngeset Correct `with` or `type` are a logical OR.

**Pull request merged**
