### PR TITLE
Added Azure.VM.MigrateAMA and Azure.VMSS.MigrateAMA

### LINKED ISSUE #1792: Virtual machines and virtual machine scale sets using Log Analytics Agent should switch to Azure Monitor Agent
# Rule request

## Suggested rule change

Virtual machines and virtual machine scale sets using `Log Analytics Agent` should switch to `Azure Monitor Agent`.

The Log Analytics agent (also known as MMA and OMS) will be retired on  `August 31, 2024`.

Azure Monitor Agent (AMA) replaces the Log Analytics agent. The new agent has many benefits in terms of `security`, `performance`, `cost savings` and `management`.

`Operational excellence` pillar suits this nicely.

## Applies to the following

The rule applies to the following:

- Resource type: **[Microsoft.Compute/virtualMachines]**
- Resource type: **[Microsoft.Compute/virtualMachineScaleSets]**

## Additional context

[Log Analytics agent retiring](https://azure.microsoft.com/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/)
[Migrate to Azure Monitor Agent from Log Analytics agent](https://learn.microsoft.com/azure/azure-monitor/agents/azure-monitor-agent-migration)

### PR DESCRIPTION
**Pull request by bengeset96**
## PR Summary

Fixes  #1792

Added Azure.VM.MigrateAMA and Azure.VMSS.MigrateAMA rules.

Rules used to ensure that virtual machines and virtual machine scale sets using the new modern `Azure Monitor Agent` instead of the old legacy agent `Log Analytics Agent`. 

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by BernieWhite** [comment]
@bengeset96 The message `Conditions must return boolean $True or $False.` is returned when an object is returned as a result of the result. Only `$True` or `$False` or using `$Assert` is allowed.

If you are executing something like `@(GetSubResources -ResourceType 'Microsoft.Compute/virtualMachines/extensions', 'Microsoft.Compute/virtualMachineScaleSets/extensions' | Where-Object { $_.Properties.publisher -eq 'Microsoft.EnterpriseCloud.Monitoring' -and $_.Properties.type -eq 'MicrosoftMonitorAgent' })` be sure that it is assigned to a variable like:

```powershell
$extensions = @(GetSubResources -ResourceType 'Microsoft.Compute/virtualMachines/extensions', 'Microsoft.Compute/virtualMachineScaleSets/extensions' | Where-Object { $_.Properties.publisher -eq 'Microsoft.EnterpriseCloud.Monitoring' -and $_.Properties.type -eq 'MicrosoftMonitorAgent' })
```

Otherwise it will be returned as the rule result.

**Comment by bengeset96** [comment]
> @bengeset96 The message `Conditions must return boolean $True or $False.` is returned when an object is returned as a result of the rule. Only `$True` or `$False` or using `$Assert` is allowed.
> 
> If you are executing something like `@(GetSubResources -ResourceType 'Microsoft.Compute/virtualMachines/extensions', 'Microsoft.Compute/virtualMachineScaleSets/extensions' | Where-Object { $_.Properties.publisher -eq 'Microsoft.EnterpriseCloud.Monitoring' -and $_.Properties.type -eq 'MicrosoftMonitorAgent' })` be sure that it is assigned to a variable like:
> 
> ```powershell
> $extensions = @(GetSubResources -ResourceType 'Microsoft.Compute/virtualMachines/extensions', 'Microsoft.Compute/virtualMachineScaleSets/extensions' | Where-Object { $_.Properties.publisher -eq 'Microsoft.EnterpriseCloud.Monitoring' -and $_.Properties.type -eq 'MicrosoftMonitorAgent' })
> ```
> 
> Otherwise it will be returned as the rule result.

Thanks, understandable.

In this case it happends due to `-If { Helper function }` I assume.

`Rule 'Azure.VM.AMA' -Ref 'AZR-000317' -Type 'Microsoft.Compute/virtualMachines' -If { HasLogAnalyticsAgent } -Tag @{ release = 'GA'; ruleSet = '2022_12' } {
    $Assert.Fail($LocalizedData.LogAnalyticsAgentDeprecated)
}`

`function global:HasLogAnalyticsAgent {
    [CmdletBinding()]
    [OutputType([System.Boolean])]
    param ()
    process {
        @(GetSubResources -ResourceType 'Microsoft.Compute/virtualMachines/extensions', 'Microsoft.Compute/virtualMachineScaleSets/extensions' |
            Where-Object { $_.Properties.publisher -eq 'Microsoft.EnterpriseCloud.Monitoring' })    
    } 
}`

I'll try to troubleshoot further as I'd assume `$Assert.Fail()` here is valid.

**Comment by bengeset96** [comment]
@BernieWhite 

Would be truly grateful if you had the chance to review this =)

**Review by BernieWhite — APPROVED** [review]
Thanks @bengeset96, great work! All good to merge.

**Pull request merged**
