### PR TITLE
Added Azure.FrontDoor.UseCaching

### LINKED ISSUE #548: Enable caching to accelerate Front Door traffic
# Rule request

## Suggested rule change

Use caching for each Front Door route rule to reduce latency and minimize calls to backend systems.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Network/frontDoors**

## Additional context

[Caching with Azure Front Door](https://docs.microsoft.com/azure/frontdoor/front-door-caching)

### PR DESCRIPTION
**Pull request by bengeset96**
## PR Summary

Fixes #548 

Added Azure.FrontDoor.UseCaching rule.

This rule ensures that front door instances uses caching to reduce retrieving contents from origins and improve overall performance.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by bengeset96** [comment]
@BernieWhite 

Can be reviewed.

If any questions or something is unclear on what I have done, please reach out so we can address it.

**Review by BernieWhite — CHANGES_REQUESTED** [review]
@bengeset96 Looks great! The only comment I have is that we should add `NOTES` section to call out that this rule only applies to Front Door Classic. Similar to: https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/en/rules/Azure.ACR.ContainerScan.md#notes

**Comment by bengeset96** [comment]
@BernieWhite 

I can do that. The reason for not originally using `-If` was to have all tiers targeted.

I assume you mean to call out that the ruly does **not** apply to Front Door Classic tier?

**Comment by BernieWhite** [comment]
> @BernieWhite
> 
> I can do that. The reason for not originally using `-If` was to have all tiers targeted.
> 
> I assume you mean to call out that the ruly does **not** apply to Front Door Classic tier?

Front Door Classic (`Microsoft.Network/frontDoors`) and Front Door Standard/ Premium (`Microsoft.Cdn/profiles`) use different resource types.

**Comment by bengeset96** [comment]
> > @BernieWhite
> > I can do that. The reason for not originally using `-If` was to have all tiers targeted.
> > I assume you mean to call out that the ruly does **not** apply to Front Door Classic tier?
> 
> Front Door Classic (`Microsoft.Network/frontDoors`) and Front Door Standard/ Premium (`Microsoft.Cdn/profiles`) use different resource types.

I will check before moving forward, I was not aware. Thanks for the information.

I'll see if I can also add support for Standard and Premium tier. I assume that I'll find something similar in terms of enabling or disabling caching.

**Comment by bengeset96** [comment]
@BernieWhite 

Notes section has been added, ready for merge.

I'll create something for Standard and Premium tier as well as it is possible to enable or disable caching.

As these are different resource types I think it makes most sense to have them seperated.

New PR will be created for this once I have gotten it.

**Review by BernieWhite — APPROVED** [review]
@bengeset96 Nice work! All good to merge.

**Pull request merged**
