### PR TITLE
Added support in Azure.AKS.Version for ignoring clusters with auto-upgrade enabled

### LINKED ISSUE #1918: Ignore Azure.AKS.Version for clusters with auto-upgrade enabled
# Rule request

## Suggested rule change

For managed clusters with auto-upgrade enabled (`rapid`/ `stable`/ `node-image`) the specific version installed for the cluster API server should be ignored unless the evaluation it occurring against an in-flight resource.

Update the existing `Azure.AKS.Version` rule to improve this behaviour.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.ContainerService/managedClusters**

### PR DESCRIPTION
**Pull request by BenjaminEngeset**
## PR Summary

Fixes #1918 

Added support in Azure.AKS.Version for ignoring clusters with auto-upgrade enabled.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by BenjaminEngeset** [comment]
Hey @BernieWhite

Currently working on this one.

Could you check the logic here when you have the time. I'm unsure if you're thinking that we still should have these AKS clusters on the rule so customers can see that they passed the rule, or if they should be fully excluded from the rule completely.

**Comment by BernieWhite** [comment]
> Hey @BernieWhite
> 
> Currently working on this one.
> 
> Could you check the logic here when you have the time. I'm unsure if you're thinking that we still should have these AKS clusters on the rule so customers can see that they passed the rule, or if they should be fully excluded from the rule completely.

The logic looks great.

**Comment by BenjaminEngeset** [comment]
@BernieWhite 

Ready for review.

**Review by BernieWhite — APPROVED** [review]
Great work @BenjaminEngeset. All good to merge.

**Pull request merged**
