### PR TITLE
Added Azure.ServiceBus.MinTLS

### LINKED ISSUE #1777: Service Bus should minimum use TLS 1.2 version
# Rule request

## Suggested rule change

It is now possible to control the minimum TLS version that is used with service bus namespace.

Minimum should be TLS 1.2 to enforce stricter security measures.

Important to have good documentation for customers on this one. If a Service Bus namespace requires a minimum version of TLS, then any requests made with an older version will fail.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.ServiceBus/namespaces**

## Additional context

[Control minimum TLS version now GA](https://azure.microsoft.com/en-us/updates/announcing-policy-to-control-the-minimum-tls-version-used-with-azure-service-bus-now-ga/)
[Enforce a minimum required version of TLS for request to a service bus namespace](https://learn.microsoft.com/en-us/azure/service-bus-messaging/transport-layer-security-enforce-minimum-version)
[Template reference](https://learn.microsoft.com/en-us/azure/templates/Microsoft.ServiceBus/namespaces?pivots=deployment-language-bicep)

### PR DESCRIPTION
**Pull request by bengeset96**
## PR Summary

Fixes #1777 

Added Azure.ServiceBus.MinTLS rule.

This rule checks for that service bus namespaces uses minimum TLS 1.2 version.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by bengeset96** [comment]
@BernieWhite 

:shipit: or some adjustments to be carried out?

**Review by BernieWhite — CHANGES_REQUESTED** [review]
@bengeset96 Nice work! Looks great. The only suggestion would be to update one of the existing test cases such as `servicens-B` to use TLS 1.0 for improved test coverage.

So we have:

- `servicens-A` with no TLS version specified.
- `servicens-B` with TLS 1.0.
- `servicens-C` with TLS 1.2.

**Comment by bengeset96** [comment]
@BernieWhite 

Adjusted, think we're set for merge now.

**Review by BernieWhite — APPROVED** [review]
@bengeset96 Great work. All good to merge.

**Pull request merged**
