### PR TITLE
feat: Added Azure.PostgreSQL.ZoneRedundantHA

### LINKED ISSUE #2932: [RULE] Deploy Azure Database for PostgreSQL servers using zone-redundant high availability (HA) in supported regions to ensure high availability and resilience
### Existing rule

_No response_

### Suggested rule

Azure Database for PostgreSQL flexible servers allows configuration high availablity (HA) across availablity zones in supported regions.
Using availability zones improves resiliency of your solution to failures or disruptions isolated to a zone or data center.

### Pillar

Reliability

### Additional context

- [RE:05 Regions and availability zones](https://learn.microsoft.com/azure/well-architected/reliability/regions-availability-zones)
- [High availability concepts in Azure Database for PostgreSQL](https://learn.microsoft.com/azure/reliability/reliability-postgresql-flexible-server)
- [Zone-redundant HA architecture](https://learn.microsoft.com/azure/reliability/reliability-postgresql-flexible-server#availability-zone-support)
- [Azure deployment reference](https://learn.microsoft.com/azure/templates/microsoft.dbforpostgresql/flexibleservers)

### PR DESCRIPTION
**Pull request by BenjaminEngeset**
## PR Summary

Fixes #2932

Added Azure.PostgreSQL.ZoneRedundantHA.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by BenjaminEngeset** [comment]
Ready for review @BernieWhite. Not everything here is identical as MySQL regarding the documentation as there are some different behaviors, please check it out.

I'm actually a bit confused about the storage part. Looks like the ZRS storage is only used for backup from the servers and never read from, before, under or after failover. Looks like the primary server is just sending of data to the secondary all time being, ensuring that both theirs LRS storage is identical.

**Comment by BernieWhite** [comment]
> erything here is identical as

The data is being replicated between the two servers by a PostgreSQL shipping transaction logs to the standby but using a PostgreSQL implementation instead of replication of storage by Azure.

So each server has separate LRS storage for the database, with PostgreSQL replicating the data at the application level to keep them in sync, with ZRS storage being used for backups.

In the event of failure, the standby would recovery any transaction logs and bring the standby online.

**Review by BernieWhite — APPROVED** [review]
Thanks @BenjaminEngeset LGTM. All good to merge.

**Comment by BenjaminEngeset** [comment]
> @BenjaminEngeset
> 
> The data is being replicated between the two servers by a PostgreSQL shipping transaction logs to the standby but using a PostgreSQL implementation instead of replication of storage by Azure.
> 
> So each server has separate LRS storage for the database, with PostgreSQL replicating the data at the application level to keep them in sync, with ZRS storage being used for backups.
> 
> In the event of failure, the standby would recovery any transaction logs and bring the standby online.

Great, thanks!

**Pull request merged**
