### PR TITLE
Added Azure.VM.ASDistributeTraffic

### LINKED ISSUE #67: VMs in an availablity set should use a load balancer or application gateway
# Rule request

## Suggested rule change

VMs in an availability set should use a load balancer or application gateway to distribute traffic as part of a backend pool.

## Applies to the following

The rule applies to the following:

- Resource type: **Microsoft.Compute/virtualMachines**

### PR DESCRIPTION
**Pull request by BenjaminEngeset**
## PR Summary

Fixes #67

Added Azure.VM.ASDistributeTraffic.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by BenjaminEngeset** [comment]
Ready for review, @BernieWhite.

This one is a bit special, as in all honesty, configuring virtual network card interfaces within the resource itself is not so common and should not be recommended really. Cannot even decide the full name for the NIC. It's not possible to configure `properties.networkProfile.networkInterfaceConfigurations` and `properties.networkProfile.networkInterfaces` at the same time within a template either.

After the deployment by using `properties.networkProfile.networkInterfaceConfigurations`,  the property is gone in the template and the `properties.networkProfile.networkInterfaces` is created with the NICs that the interface configuration created.

So the rule is not really that useful for scenarios when exporting.

Let me know what you think. This is not an ideal rule, but I think it's not possible to do anything else?

**Comment by BernieWhite** [comment]
> 'Microsoft.Network/networkInterfaces'

Only for in-flight cases.

**Comment by BenjaminEngeset** [comment]
> > 'Microsoft.Network/networkInterfaces'
> 
> Only for in-flight cases. But this rule is only going to be applicable for in-flight cases.

Gotcha. Update from me soon, I will notify you when I am done.

**Comment by BenjaminEngeset** [comment]
Ready for review @BernieWhite.

As it is now each IP configuration requires to reference a pool, otherwise it will fail.

The rule can also be designed so that one IP configuration referencing a pool is enough.

**Pull request merged**
