### PR TITLE
feat(new): Added Azure.Cosmos.DisableLocalAuth

### LINKED ISSUE #2846: [RULE] Cosmos DB No SQL API should disable local auth
### Existing rule

_No response_

### Suggested rule

Use OAuth2/ Entra ID identities for accessing data and disable access using cryptographic keys.

This only currently applies to the No SQL API.

### Pillar

Security

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BenjaminEngeset**
## PR Summary

Fixes #2846

Added Azure.Cosmos.DisableLocalAuth.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by BenjaminEngeset** [comment]
Ready for review @BernieWhite 👍

**Comment by BenjaminEngeset** [comment]
Should be good now @BernieWhite after update.

**Comment by BenjaminEngeset** [comment]
@BernieWhite I had some mess included from another branch, should be cleaned up now. Sorry for the mess.

**Review by BernieWhite — CHANGES_REQUESTED** [review]
Great work @BenjaminEngeset. Just a few suggested changes below to round this out.

**Comment by BenjaminEngeset** [comment]
Great @BernieWhite. Adjusted accordingly to the suggestions now.

**Review by BernieWhite — APPROVED** [review]
Thanks @BenjaminEngeset. All good to merge.

**Pull request merged**
