### PR TITLE
Added Azure.APIM.DefenderCloud

### LINKED ISSUE #2187: Check APIs published in Azure API management is using Defender for APIs
### Existing rule

_No response_

### Suggested rule

APIs published in Azure API Management can be secured by Defender for APIs. All tiers of APIM supports Defender for APIs.

It offers full lifecycle protection, detection, and response coverage for APIs.

Defender for APIs can be onboarded in the Defender for Cloud portal, or within the API Management instance in the Azure portal.

With infrastructure as code this is done by creating an sub-resource `Microsoft.Security/apiCollections` under `Microsoft.ApiManagement/service`. The collection (Defender for APIs resource) must have the same name as the API published in Azure API Management. This will initiate an diagnostics setting on the API as well.

Defender for APIs is currently in preview.

Defender for APIs currently doesn't onboard APIs that are exposed using the API Management [self-hosted gateway](https://learn.microsoft.com/en-us/azure/api-management/self-hosted-gateway-overview), or managed using API Management [workspaces](https://learn.microsoft.com/en-us/azure/api-management/workspaces-overview).

Currently Defender for APIs only discovers and analyzes REST APIs.

### Pillar

Security

### Additional context

https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-apis-introduction
https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-apis-prepare
https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-apis-deploy
https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-apis-posture
https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-apis-manage
https://learn.microsoft.com/en-us/azure/templates/microsoft.security/apicollections

### PR DESCRIPTION
**Pull request by BenjaminEngeset**
## PR Summary

Fixes #2187

Added Azure.APIM.DefenderCloud rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by BenjaminEngeset** [comment]
@BernieWhite Let me know your thoughts.

**Comment by BenjaminEngeset** [comment]
@BernieWhite Fixed the failing tests now fyi.

**Review by BernieWhite — CHANGES_REQUESTED** [review]
Thanks @BenjaminEngeset. Correct me if I'm wrong but I think `apim-B` should be failing instead of passing.

Maybe double check the logic with the suggestions below.

**Comment by BenjaminEngeset** [comment]
> Thanks @BenjaminEngeset. Correct me if I'm wrong but I think `apim-B` should be failing instead of passing.
> 
> Maybe double check the logic with the suggestions below.

Hi @BernieWhite! I am a bit confused, `apim-B` is failing? I also tried to build again, it fails. Where did you see it pass, tried to check older CI runs. I have added the suggested logic anyways as the method really fits perfect into the scenario and makes it a bit more readable.


```
$ruleResult = @($filteredResult | Where-Object { $_.Outcome -eq 'Fail' });
$ruleResult.TargetName
apim-A
apim-B
apim-C
```

**Review by BernieWhite — APPROVED** [review]
Thanks @BenjaminEngeset. I think I got confused with one of the other tests. All good to merge.

**Pull request merged**
