### PR TITLE
Created Spanish documentation

### PR DESCRIPTION
**Pull request by jonathanruiz**
## PR Summary

Started Spanish documentation of the rules. 
- Created documentation for all Azure.ACR rules.
- Updated the pipeline to check for es, es-us culture tags.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [] Change is not breaking
- [ ] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by jonathanruiz** [comment]
@BernieWhite, I've started the Spanish documentation of the rules. Although all the checks pass, it is not ready to merge. If I update the `ps-rule.yaml` file on `Line 36` to `es-us`, several errors are thrown for every rule stating the following:

    [FAIL] Rule.Help

    | REASON:
    | - Path Info.Description: Is null or empty.
    | - Path Info.Recommendation: Is null or empty.

    [FAIL] Rule.Pillar

    | REASON:
    | - Path Info.Annotations.pillar: Does not exist.
    | - Path Info.Annotations.pillar: Does not exist.

    [FAIL] Rule.Annotations

    | REASON:
    | - Path Info.Annotations.severity: Does not exist.
    | - Path Info.Annotations.category: Does not exist.
    | - Path Info.Annotations.resource: Does not exist.

    [FAIL] Rule.OnlineHelp

    | REASON:
    | - Path Info.Annotations.'online version': Does not exist.
    | - Path Info.Annotations.'online version': Does not exist.
    | - Path Info.Annotations.'online version': Does not exist.

I will point out that I have updated the `pipeline.build.ps1` and the '.ps-rule\Rule.Rule.ps1' files to attempt to make checks for `es-us` culture. Any idea of what next steps for the pipeline?

**Comment by BernieWhite** [comment]
@jonathanruiz Very cool. Thanks for helping out with this. Hmm yes that does bring up a few issues. Currently PSRule would look at the markdown file and specifically look for English headings when parsing the document over here: https://github.com/microsoft/PSRule/blob/main/src/PSRule/Resources/DocumentStrings.resx

We could use English headings then update the web publishing code here: https://github.com/Azure/PSRule.Rules.Azure/blob/f3096e2e62f86335f63de5f30b66977ad0470055/docs/hooks.py#L26-L31

Ultimately we should probably do both and that may uncover more issues :) but good to get these resolved.

Would you like to have a go a creating a new resx file over in the PSRule repo? https://github.com/microsoft/PSRule

Files are named based on `<FullTypeName><.Locale>.resx`, so it should be something like: `DocumentStrings.es.resx` or `DocumentStrings.es-US.resx`. PSRule follows a similar pattern so maybe paths should be `es` instead.

https://learn.microsoft.com/en-us/dotnet/core/extensions/localization#resource-files

The ordering might be important but since I don't understand Spanish I'll take your guidance. If you use `es` then this would be used for any dialect of Spanish. If you use `es-US` only people using the US dialect of Spanish would get the translations, other Spanish dialects would default back to English.

In my mind, it's probably better to use any Spanish, even if it is not 100% correct then no Spanish.

**Comment by jonathanruiz** [comment]
@BernieWhite, with the changes now made in [PSRule PR #1288](https://github.com/microsoft/PSRule/pull/1288), what changes need to made in this repo for it to be ready to merge?

**Comment by BernieWhite** [comment]
@jonathanruiz I think if you update this branch from main you should be able to use the Spanish translations.

In terms of additional updates. We should ideally build some tests to make sure that the translated files work and update the help site to allow viewing of docs in Spanish.

You could try adding some test similar to: https://github.com/microsoft/PSRule/blob/2d9ae08edaf3c9b017d6928ee905e42b8259c720/tests/PSRule.Tests/PSRule.Common.Tests.ps1#L2094-L2161

Otherwise happy to merge it as is and I'll add some tests.

**Comment by jonathanruiz** [comment]
@BernieWhite the branch has been updated from main and ready for Code Review. I am currently working on updating the Rules in the PSRule repo to check for Spanish.

**Review by BernieWhite — APPROVED** [review]
Thanks @jonathanruiz. All good to merge.

**Pull request merged**
