### PR TITLE
Added Azure.PostgreSQL.AAD

### LINKED ISSUE #2226: Azure MySQL single and flexible servers should have AAD authentication configured
### Existing rule

_No response_

### Suggested rule

AAD authentication improves security by ensuring that Azure MySQL flexible servers can be accessed by Azure Active Directory identities which are far more secure than local methods.

This is supported for both single and flexible servers deployment model.

### Pillar

Security

### Additional context
https://learn.microsoft.com/en-us/azure/mysql/single-server/concepts-azure-ad-authentication
https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-azure-ad-authentication
https://learn.microsoft.com/en-us/azure/templates/microsoft.dbformysql/servers/administrators
https://learn.microsoft.com/en-us/azure/templates/microsoft.dbformysql/flexibleservers/administrators

### LINKED ISSUE #2249: Azure PostgreSQL single and flexible servers should have AAD authentication configured
### Existing rule

_No response_

### Suggested rule

AAD authentication improves security by ensuring that Azure PostgreSQL databases can be accessed by Azure Active Directory identities which are far more secure than local methods.

This is supported for both single and flexible servers deployment model.

### Pillar

Security

### Additional context

- [Use modern password protection](https://learn.microsoft.com/azure/architecture/framework/security/design-identity-authentication#use-modern-password-protection)
- [Azure Active Directory Authentication with PostgreSQL Flexible Server](https://learn.microsoft.com/azure/postgresql/flexible-server/concepts-azure-ad-authentication#how-azure-ad-works-in-flexible-server)
- [Use Azure AD for authentication with Azure Database for PostgreSQL - Flexible Server](https://learn.microsoft.com/azure/postgresql/flexible-server/how-to-configure-sign-in-azure-ad-authentication)
- [Use Azure AD for authentication with Azure Database for PostgreSQL - Single Server](https://learn.microsoft.com/azure/postgresql/single-server/how-to-configure-sign-in-azure-ad-authentication)
- [Azure Active Directory Authentication (Single Server VS Flexible Server)](https://learn.microsoft.com/azure/postgresql/flexible-server/concepts-azure-ad-authentication#azure-active-directory-authentication-single-server-vs-flexible-server)
- [Azure security baseline for Azure Database for PostgreSQL - Flexible Server](https://learn.microsoft.com/security/benchmark/azure/baselines/azure-database-for-postgresql-flexible-server-security-baseline)
- [Azure security baseline for Azure Database for PostgreSQL - Single Server](https://learn.microsoft.com/security/benchmark/azure/baselines/postgresql-security-baseline)
- [IM-1: Use centralized identity and authentication system](https://learn.microsoft.com/security/benchmark/azure/baselines/azure-database-for-postgresql-flexible-server-security-baseline#im-1-use-centralized-identity-and-authentication-system)
- [Azure deployment reference Flexible Server](https://learn.microsoft.com/azure/templates/microsoft.dbforpostgresql/flexibleservers/administrators)
- [Azure deployment reference Single Server](https://learn.microsoft.com/azure/templates/microsoft.dbforpostgresql/servers/administrators)

### PR DESCRIPTION
**Pull request by BenjaminEngeset**
## PR Summary

Fixes #2249

Added Azure.PostgreSQL.AAD rule.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by BenjaminEngeset** [comment]
@BernieWhite Ready for review. PSRule emits to the warning stream, but it seems to work fine.

```
WARNING: Inconclusive result reported for 'server-A' @PSRule.Rules.Azure\Azure.PostgreSQL.AAD.
WARNING: Inconclusive result reported for 'server-D' @PSRule.Rules.Azure\Azure.PostgreSQL.AAD.
```

Also, `$ruleResult[1].Reason` and `$ruleResult[2].Reason` is empty, but I have seen this behaviour for some other rules as well.

**Comment by BernieWhite** [comment]
> @BernieWhite Ready for review. PSRule emits to the warning stream, but it seems to work fine.
> 
> ```
> WARNING: Inconclusive result reported for 'server-A' @PSRule.Rules.Azure\Azure.PostgreSQL.AAD.
> WARNING: Inconclusive result reported for 'server-D' @PSRule.Rules.Azure\Azure.PostgreSQL.AAD.
> ```
> 
> Also, `$ruleResult[1].Reason` and `$ruleResult[2].Reason` is empty, but I have seen this behaviour for some other rules as well.

The inconclusive warning means that no pass or fail was returned from the rule. I think the issue is `foreach ($config in $configs)`. If there is 0 configs the `foreach` will not be executed and will not call any assertion methods. Maybe add the logic to the `if` block.

**Comment by BenjaminEngeset** [comment]
@BernieWhite You were right. I have added in handling for these scenarios now. Ready for review.

**Review by BernieWhite — APPROVED** [review]
Thanks @BenjaminEngeset. Great work. All good to merge.

**Pull request merged**
