### PR TITLE
feat(new): Added Azure.VNET.NAT

### LINKED ISSUE #3003: [RULE] Use Azure NAT gateway for outbound access for virtual machines
### Existing rule

_No response_

### Suggested rule

By default, virtual machines (VMs) created in a virtual network without explicit outbound connectivity are assigned a default outbound public IP address. This IP address enables outbound connectivity to the internet.

Default Routing Behavior:
The subnet has a system default route that routes traffic with the destination 0.0.0.0/0 to the internet.
Normally, when this route is chosen, the traffic is NATed using either a default public IP address or the VM’s public IP address (if it exists) before being sent to the internet.

Behavior with NAT Gateway:
Once a NAT gateway is associated with the subnet, the behavior changes. Although the system default route will still have the next hop set to the internet, traffic is first sent to the NAT gateway.
The NAT gateway receives the traffic from the VMs in the subnet, NATs the traffic using its own public IP address, and then sends it to the internet.

The recommended method is to use NAT gateway as the explicit method of public connectivity for virtual machines to ensure security, explicit connectivity, and stability.

Also highly relevant for AKS clusters.

### Pillar

Security

### Additional context

- [SE:06 Network controls](https://learn.microsoft.com/azure/well-architected/security/networking)
- [Azure NAT Gateway](https://learn.microsoft.com/azure/nat-gateway/nat-overview)
- [Associate a NAT gateway to the subnet](https://learn.microsoft.com/azure/load-balancer/load-balancer-outbound-connections#2-associate-a-nat-gateway-to-the-subnet)
- [Default outbound access](https://learn.microsoft.com/azure/virtual-network/ip-services/default-outbound-access)
- [Azure deployment reference - Virtual Network](https://learn.microsoft.com/azure/templates/microsoft.network/virtualnetworks)
- [Azure deployment reference - Subnet](https://learn.microsoft.com/azure/templates/microsoft.network/virtualnetworks/subnets)

### PR DESCRIPTION
**Pull request by BenjaminEngeset**
## PR Summary

Fixes #3003

Added Azure.VNET.NAT.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] Change is not breaking
- [x] This PR is ready to merge and is not **Work in Progress**
- **Rule changes**
  - [x] Unit tests created/ updated
  - [x] Rule documentation created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section
- **Other code changes**
  - [ ] Unit tests created/ updated
  - [ ] Link to a filed issue
  - [ ] [Change log](https://github.com/Azure/PSRule.Rules.Azure/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

**Comment by BenjaminEngeset** [comment]
Ready for review @BernieWhite.

The rule is initially created for used-managed virtual machines, but there are other services that can take advantage of this as well.

**Comment by BernieWhite** [comment]
@BenjaminEngeset this one is a little more nuanced.

When a customer starts deploying multiple workloads for most cases they should be thinking about using a VWAN or hub and spoke network with a central Azure Firewall or NVA for controlling east/ west and north/ south traffic, following something like the cloud adoption framework. As a result, every subnet shouldn't have a NAT gateway attached. Realistically the number of internet egress points should be minimized.

You could say that anything in the VNET hub should have a NAT gateway, but even then, there is cases when this is not ideal.

- NAT Gateway is zonal, so you should deploy one in each AZ you deploy to, but with something like Azure Firewall that supports zone redundancy deploying a single NAT gateway (only one can be deployed in a subnet) could decrease the availability of outbound traffic if the zone that failed was the same as the NAT gateway.
- In the NVA configuration, there is often a private and public subnet used in-front and behind the NVA instances. The NAT gateway should only be deployed on the public subnet.

So, I'm not sure if we can reliability detect the cases from code the cases that should use a NAT gateway.

Did you have any further thoughts on this?

**Comment by BenjaminEngeset** [comment]
> @BenjaminEngeset this one is a little more nuanced.
> 
> When a customer starts deploying multiple workloads for most cases they should be thinking about using a VWAN or hub and spoke network with a central Azure Firewall or NVA for controlling east/ west and north/ south traffic, following something like the cloud adoption framework. As a result, every subnet shouldn't have a NAT gateway attached. Realistically the number of internet egress points should be minimized.
> 
> You could say that anything in the VNET hub should have a NAT gateway, but even then, there is cases when this is not ideal.
> 
> * NAT Gateway is zonal, so you should deploy one in each AZ you deploy to, but with something like Azure Firewall that supports zone redundancy deploying a single NAT gateway (only one can be deployed in a subnet) could decrease the availability of outbound traffic if the zone that failed was the same as the NAT gateway.
> * In the NVA configuration, there is often a private and public subnet used in-front and behind the NVA instances. The NAT gateway should only be deployed on the public subnet.
> 
> So, I'm not sure if we can reliability detect the cases from code the cases that should use a NAT gateway.
> 
> Did you have any further thoughts on this?

I agree with you @BernieWhite and I am truly grateful for your honest feedback.

What I can do instead is to create a new issue and new rule regarding `AzureFirewallSubnet` that is towards mitigating port exhaustion, so zonal-deployed firewalls can use a NAT gateway, if needing more than `1248000` connections at a time for an instance.

What do you think about that? There is official documentation for this.

https://learn.microsoft.com/en-us/azure/firewall/integrate-with-nat-gateway

**Comment by BernieWhite** [comment]
> > @BenjaminEngeset this one is a little more nuanced.
> > When a customer starts deploying multiple workloads for most cases they should be thinking about using a VWAN or hub and spoke network with a central Azure Firewall or NVA for controlling east/ west and north/ south traffic, following something like the cloud adoption framework. As a result, every subnet shouldn't have a NAT gateway attached. Realistically the number of internet egress points should be minimized.
> > You could say that anything in the VNET hub should have a NAT gateway, but even then, there is cases when this is not ideal.
> > 
> > * NAT Gateway is zonal, so you should deploy one in each AZ you deploy to, but with something like Azure Firewall that supports zone redundancy deploying a single NAT gateway (only one can be deployed in a subnet) could decrease the availability of outbound traffic if the zone that failed was the same as the NAT gateway.
> > * In the NVA configuration, there is often a private and public subnet used in-front and behind the NVA instances. The NAT gateway should only be deployed on the public subnet.
> > 
> > So, I'm not sure if we can reliability detect the cases from code the cases that should use a NAT gateway.
> > Did you have any further thoughts on this?
> 
> I agree with you @BernieWhite and I am truly grateful for your honest feedback.
> 
> What I can do instead is to create a new issue and new rule regarding `AzureFirewallSubnet` that is towards mitigating port exhaustion and less administrative overhead, so zonal-deployed firewalls can use a NAT gateway What do you think about that? There is official documentation for this.
> 
> https://learn.microsoft.com/en-us/azure/firewall/integrate-with-nat-gateway

Yes #3005 #3006 is a good idea.

**Pull request closed without merging**
